#!/bin/bash
docker run --rm -p 18630:18630 -d --name streamsets streamsets/datacollector || true
#docker start streamsets || true
sleep 10s

python sdc-util.py import-pipeline --dest dev \
  --pipelineJson test/testpipeline.json \
  --pipelineId firstpipe

python sdc-util.py export-pipeline --src dev \
  --out sdc.json \
  --pipelineId firstpipe

python sdc-util.py promote-pipeline --src dev \
  --srcPipelineId firstpipe \
  --dest dev

#docker stop streamsets
