#!/bin/bash
set -e
cd "$(dirname "$0")"
[[ ! "$(docker ps -a | grep streamsets)" ]] \
    && docker start streamsets || docker run --rm -p 18630:18630 -d --name streamsets streamsets/datacollector \
    && sleep 2s

# poll for streamsets availability
echo "Awaiting the docker container"
until python ../sdc-util.py system info --src production > /dev/null 2>&1
do
  echo "."
  sleep 2s
done

python ../sdc-util.py pipeline import --dest production \
  --pipelineJson testpipeline.json \
  --pipelineId firstpipe

[ ! -d test-results ] && mkdir test-results

python ../sdc-util.py pipeline export --src production \
  --out test-results/pipeline-out.json \
  --pipelineId firstpipe

python ../sdc-util.py pipeline promote --src production \
  --srcPipelineId firstpipe \
  --dest production

docker stop streamsets
